[iOS] dive deeper to the pictures
Countly/countly-sdk-ios pull request #276
Opened 2024-01-18 18:33 UTC by arifBurakDemiray

2024-01-29 08:23 UTC, turtledreams approved these changes

2024-01-29 09:57 UTC, ijunaid requested changes

2024-01-29 09:57 UTC, ijunaid commented on CountlyConnectionManager.m
> +        request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:serverInputEndpoint]];
We are already creating a URLRequest on line 209 without checking the picture upload data without any checks, i think its better to use if else something like this for line 202-213: 
`NSString* serverInputEndpoint = [self.host stringByAppendingString:endPoint];
if (!pictureUploadData)
    {
        queryString = [self appendChecksum:queryString];
        NSString* fullRequestURL = [serverInputEndpoint stringByAppendingFormat:@"?%@", queryString];
    NSMutableURLRequest* request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:fullRequestURL]];
    }
    else {
        request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:serverInputEndpoint]];
        ....
        ...
        ...
        }
    `

2024-01-29 09:57 UTC, ijunaid commented on CountlyConnectionManager.m
> -    mutableRequestParameters[@"dr"] = [NSNumber numberWithInt:1];
Just curious why we have removed this?

2024-01-29 09:57 UTC, ijunaid commented on CountlyConnectionManager.m
> +    NSString* boundaryStart = [NSString stringWithFormat:@"\r\n--%@\r\n", kCountlyUploadBoundary];
I am not sure about it but is it a right way to add boundary start on every Multipart and then only one boundary end for all of them?

2024-02-02 12:31 UTC, ijunaid approved these changes

2024-02-02 12:40 UTC, merged