Enhanced segmentation values to include additional supported data types beyond NSString.
Countly/countly-sdk-ios pull request #312
Opened 2024-06-24 14:23 UTC by ijunaid

2024-06-25 07:43 UTC, arifBurakDemiray commented on CountlyCommon.m
> +        if ([obj isKindOfClass:[NSNumber class]] || [obj isKindOfClass:[NSString class]]) {
what about float, long or other types. Is Number parent class of them?

2024-06-25 07:45 UTC, arifBurakDemiray reviewed
Looks cool, needs testing,
Arigato J-aniki

2024-06-27 05:08 UTC, turtledreams requested changes

2024-06-27 05:08 UTC, turtledreams commented on CountlyTests/CountlySegmentationTests.swift
> +
cant we verify 'arrayKey' more precisely?

2024-06-28 03:51 UTC, turtledreams approved these changes

2024-06-28 07:15 UTC, arifBurakDemiray approved these changes

2024-06-30 11:33 UTC, merged