Send an empty location if location is disabled or location consent is not given
Countly/countly-sdk-ios pull request #322
Opened 2024-07-22 10:27 UTC by ijunaid

2024-07-22 13:13 UTC, arifBurakDemiray reviewed
this looks ok for initilization

but what about location consent revoked after init?
It should also send that info

2024-07-24 16:25 UTC, turtledreams requested changes
changelog

2024-07-25 06:56 UTC, arifBurakDemiray requested changes
Please also add some tests about all location situations.

2024-07-25 06:56 UTC, arifBurakDemiray commented on CountlyConsentManager.m
> +        [CountlyConnectionManager.sharedInstance sendLocationInfo];
Do we guarantee that we are sending empty location info?

2024-07-29 06:27 UTC, merged