Send orientation during initialization and consent given for user det…
Countly/countly-sdk-ios pull request #323
Opened 2024-07-22 17:34 UTC by ijunaid

…ails

2024-07-23 06:55 UTC, arifBurakDemiray approved these changes

2024-07-24 16:26 UTC, turtledreams requested changes
changelog

2024-07-25 06:44 UTC, arifBurakDemiray commented
Ah sorry, I have clicked to wrong place 😅

2024-07-29 06:26 UTC, turtledreams approved these changes

2024-07-29 06:26 UTC, merged