Some fixes for view duration and added tests
Countly/countly-sdk-ios pull request #347
Opened 2024-10-14 07:36 UTC by ijunaid

2024-10-14 08:07 UTC, arifBurakDemiray approved these changes

2024-10-14 08:07 UTC, arifBurakDemiray commented on CountlyTests/CountlyViewTests.swift
> +    func testViewTrackingWithBackgroundAndForegroundNotifications() throws {
addition of test comments would be great

2024-10-22 06:45 UTC, arifBurakDemiray requested changes
This is a nice addition of test suite.
It might be extended by scenarios
For example what happens after consent removal etc.

2024-10-22 06:45 UTC, arifBurakDemiray commented on CountlyTests/CountlyViewTests.swift
> +        checkRecordedEventsForView(viewName: "View1")
you may also want to validate duration of the views

2024-10-22 06:45 UTC, arifBurakDemiray commented on CountlyTests/CountlyViewTests.swift
> +        checkRecordedEventsForView(viewName: "View1", segmentation: ["key": "value"])
for example here. View must have a duration of 4 secondo

2024-10-22 06:45 UTC, arifBurakDemiray commented on CountlyTests/CountlyViewTests.swift
> +        checkRecordedEventsForView(withID: viewID)
we want to see specifically also those durations are validated and SDK correctly calculates the duration

2024-10-29 11:54 UTC, AliRKat approved these changes
cool work! looks all good to me. just couldn't be sure whether we validate each param under a view request or not but I don't think there's anything wrong with the current way

2024-10-31 09:53 UTC, turtledreams approved these changes

2024-10-31 09:55 UTC, merged